CREATE SEQUENCE DEPARTMENT_ID_SEQ INCREMENT BY 1 START WITH 100;
CREATE TABLE DEPARTMENT (
   ID              BIGINT        PRIMARY KEY    NOT NULL,
   NAME            VARCHAR       UNIQUE         NOT NULL
);

CREATE SEQUENCE EMPLOYEE_ID_SEQ INCREMENT BY 1 START WITH 100;
CREATE TABLE EMPLOYEE (
   ID              BIGINT        PRIMARY KEY    NOT NULL,
   NAME            VARCHAR       UNIQUE         NOT NULL,
   DEPARTMENT_ID   BIGINT        REFERENCES     DEPARTMENT(ID)
);
