CREATE TABLE DEPARTMENT (
  ID identity,
  NAME VARCHAR(50) not null
);

CREATE TABLE EMPLOYEE (
   ID IDENTITY,
   DEPARTMENT_ID INT,
   foreign key (DEPARTMENT_ID) references DEPARTMENT(ID),
   name VARCHAR(50) NOT NULL
);
